{
 "title": "Cluster Dashboard",
 "description": "Dashboard for GPU Clusters\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "AD", "query": "label_values(up, AD)" },
   { "name": "compartment", "query": "label_values(up, compartment)" },
   { "name": "rackID", "query": "label_values(up, rackID)" },
   { "name": "rail_id", "query": "label_values(up, rail_id)" },
   { "name": "hpc_island", "query": "label_values(up, hpc_island)" },
   { "name": "cluster_name", "query": "label_values(up, cluster_name)" },
   { "name": "oci_name", "query": "label_values(up, oci_name)" },
   {
    "name": "hostname",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL, Hostname)"
   },
   { "name": "fss_mount", "query": "label_values(up, fss_mount)" },
   {
    "name": "mountpoint",
    "query": "label_values(node_filesystem_free_bytes, mountpoint)"
   },
   {
    "name": "fstype",
    "query": "label_values(node_filesystem_free_bytes, fstype)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "interface",
    "query": "label_values(rdma_np_ecn_marked_roce_packets, interface)"
   },
   {
    "name": "gpu",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL, gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDMA Device Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rdma_device_status==0", "legendFormat": "{{hostname}} {{rdma_device}}" },
      { "expr": "rdma_device_status==1", "legendFormat": "{{hostname}} {{rdma_device}}" }
     ]
    },
    {
     "title": "RTTCC Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rttcc_status==0", "legendFormat": "{{hostname}} {{rdma_device}}" },
      { "expr": "rttcc_status==1", "legendFormat": "{{hostname}} {{rdma_device}}" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster 1m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load1)",
       "legendFormat": "1m load average {{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster 5m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load5)",
       "legendFormat": "5m load average {{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster 15m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load15)",
       "legendFormat": "15m load average {{cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance 1m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_load1{hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Instance 5m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_load5{hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Instance 15m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_load15{hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ceil((1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}/node_memory_MemTotal_bytes{hostname=~\"$hostname\"}))*100)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Storage utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ceil((1 - (node_filesystem_avail_bytes{mountpoint=~\"$mountpoint\",device!~\"rootfs\"} / node_filesystem_size_bytes{mountpoint=~\"$mountpoint\",device!~\"rootfs\"}))*100)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk reads completed iops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Disk writes completed iops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Disk read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Disk write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Time spent doing I/Os",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Network Traffic Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{hostname=~\"$hostname\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Network Traffic Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{hostname=~\"$hostname\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_total_read_bytes_total[$__range])",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_total_write_bytes_total[$__range])",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    },
    {
     "title": "Metadata IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(hostname) (rate(node_mountstats_nfs_operations_requests_total{operation!~\"READ|WRITE\"}[$__range]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(hostname) (rate(node_mountstats_nfs_operations_requests_total{operation=~\"READ|WRITE\"}[$__range]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "NFS Retransmissions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(hostname, export) (node_nfs_rpc_retransmissions_total)",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    },
    {
     "title": "NFS Request Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(hostname, export) (rate(node_mountstats_nfs_operations_request_time_seconds_total[$__range]))",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    },
    {
     "title": "NFS Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(hostname, export) (rate(node_mountstats_nfs_operations_response_time_seconds_total[$__range]))",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    },
    {
     "title": "NFS Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(hostname, export) (rate(node_mountstats_nfs_operations_queue_time_seconds_total[$__range]))",
       "legendFormat": "{{hostname}} - {{export}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "SM Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory temperature (in C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEMORY_TEMP{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "GPU temperature (in C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Power draw (in W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "watts" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total energy consumption since boot (in mJ)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "joules" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of PCIe retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_PCIE_REPLAY_COUNTER{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory Copy Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Encoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ENC_UTIL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Decoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_DEC_UTIL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Value of the last XID error encountered",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_XID_ERRORS{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Framebuffer memory free (in MiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "megabytes" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_FB_FREE{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Framebuffer memory used (in MiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "megabytes" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_FB_USED{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of NVLink bandwidth counters for all lanes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of single-bit volatile ECC errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of double-bit volatile ECC errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ECC_DBE_VOL_TOTAL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of single-bit persistent ECC errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ECC_SBE_AGG_TOTAL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of double-bit persistent ECC errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ECC_DBE_AGG_TOTAL{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Number of remapped rows for uncorrectable errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Number of remapped rows for correctable errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    },
    {
     "title": "Whether remapping of rows has failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ROW_REMAP_FAILURE{Hostname=~\"$hostname\"})",
       "legendFormat": "Host {{ Hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVLink Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total data transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_data_tx_kib{hostname=~\"$hostname\",gpu=~\"$gpu\"})",
       "legendFormat": "Total NVLink bandwidth usage by gpu {{ gpu }}"
      }
     ]
    },
    {
     "title": "Total data received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_data_rx_kib{hostname=~\"$hostname\",gpu=~\"$gpu\"})",
       "legendFormat": "Total NVLink bandwidth usage by gpu {{ gpu }}"
      }
     ]
    },
    {
     "title": "Total raw bytes transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_raw_tx_kib{hostname=~\"$hostname\",gpu=~\"$gpu\"})",
       "legendFormat": "Total NVLink bandwidth usage by gpu {{ gpu }}"
      }
     ]
    },
    {
     "title": "Total raw bytes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_raw_rx_kib{hostname=~\"$hostname\",gpu=~\"$gpu\"})",
       "legendFormat": "Total NVLink bandwidth usage by gpu {{ gpu }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ROCEv2 Port Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of data octets transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "(ib_port_xmit_data{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of data octets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "(ib_port_rcv_data{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of packets transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_port_xmit_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_port_rcv_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of unicast packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_unicast_rcv_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of unicast packets transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_unicast_xmit_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of multicast packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_multicast_rcv_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Total number of multicast packets transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(ib_multicast_xmit_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ROCEv2 Congestion Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ROCEv2 packets marked for congestion",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_np_ecn_marked_roce_packets{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of out of sequence packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_out_of_sequence{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of received NAK sequence error packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_packet_seq_err{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of times QPs ack timer expired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_local_ack_timeout_err{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of adaptive retransmissions for RoCE traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_roce_adp_retrans{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of CNP packets sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_np_cnp_sent{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of CNP packets handled to throttle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_rp_cnp_handled{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of CNP packets received and ignored",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_rp_cnp_ignored{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of RoCE packets with ICRC (Invertible Cyclic Redundancy Check) errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_rx_icrc_encapsulated{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    },
    {
     "title": "Number of times RoCE slow restart was used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_roce_slow_restart{hostname=~\"$hostname\",interface=~\"$interface\"})",
       "legendFormat": "host {{ hostname }} and nic {{ interface }}"
      }
     ]
    }
   ]
  }
 ]
}