{
 "title": "GPU RDMA NVLink Dashboard",
 "description": "Dashboard for GPU Clusters\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "Prometheus" },
   { "name": "hostname", "query": "label_values(Hostname)" },
   { "name": "device", "query": "label_values(device)" },
   { "name": "interface", "query": "label_values(interface)" },
   { "name": "cluster_name", "query": "label_values(cluster_name)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster 1m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load1)",
       "legendFormat": "1m load average {{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster 5m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load5)",
       "legendFormat": "5m load average {{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster 15m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (cluster_name) (node_load15)",
       "legendFormat": "15m load average {{cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance 1m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "(node_load1)", "legendFormat": "1m load average {{instance}}" }
     ]
    },
    {
     "title": "Instance 5m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "(node_load5)", "legendFormat": "5m load average {{instance}}" }
     ]
    },
    {
     "title": "Instance 15m load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "(node_load15)", "legendFormat": "15m load average {{instance}}" }
     ]
    },
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes))*100",
       "legendFormat": "memory utilization {{instance}}"
      }
     ]
    },
    {
     "title": "Storage utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_avail_bytes{device!~\"rootfs\"} / node_filesystem_size_bytes{device!~\"rootfs\"}))*100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total[$__rate_interval])",
       "legendFormat": "recv {{device}}"
      }
     ]
    },
    {
     "title": "Network Traffic Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total[$__rate_interval])",
       "legendFormat": "sent {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SM Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_SM_CLOCK)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEM_CLOCK)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory temperature (in C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEMORY_TEMP)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "GPU temperature (in C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_TEMP)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Power draw (in W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "watts" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_POWER_USAGE)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total energy consumption since boot (in mJ)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "joules" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of PCIe retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_PCIE_REPLAY_COUNTER)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Memory Copy Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_MEM_COPY_UTIL)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Encoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ENC_UTIL)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Decoder Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_DEC_UTIL)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Value of the last XID error encountered",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_XID_ERRORS)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Framebuffer memory free (in MiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "megabytes" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_FB_FREE)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Framebuffer memory used (in MiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "megabytes" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_FB_USED)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "vGPU License status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "counter" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_VGPU_LICENSE_STATUS)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Total number of NVLink bandwidth counters for all lanes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "counter" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Number of remapped rows for uncorrectable errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "counter" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Number of remapped rows for correctable errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "counter" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    },
    {
     "title": "Whether remapping of rows has failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "counter" } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_ROW_REMAP_FAILURE)",
       "legendFormat": "{{ Hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ROCEv2 packets marked for congestion",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rdma_np_ecn_marked_roce_packets)",
       "legendFormat": "{{ interface }}"
      }
     ]
    },
    {
     "title": "Number of out of sequence packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_out_of_sequence)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of received NAK sequence error packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_packet_seq_err)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of times QPs ack timer expired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_local_ack_timeout_err)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of adaptive retransmissions for RoCE traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_roce_adp_retrans)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of CNP packets sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_np_cnp_sent)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of CNP packets handled to throttle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_rp_cnp_handled)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of CNP packets received and ignored",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_rp_cnp_ignored)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of RoCE packets with ICRC (Invertible Cyclic Redundancy Check) errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_rx_icrc_encapsulated)", "legendFormat": "{{ interface }}" }
     ]
    },
    {
     "title": "Number of times RoCE slow restart was used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "(rdma_roce_slow_restart)", "legendFormat": "{{ interface }}" }
     ]
    }
   ]
  },
  {
   "title": "NVLink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total data in KiB transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KB" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_data_tx_kib)",
       "legendFormat": "{{ gpu }}"
      }
     ]
    },
    {
     "title": "Total data in KiB received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KB" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_data_rx_kib)",
       "legendFormat": "{{ gpu }}"
      }
     ]
    },
    {
     "title": "Total raw bytes in KiB transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KB" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_raw_tx_kib)",
       "legendFormat": "{{ gpu }}"
      }
     ]
    },
    {
     "title": "Total raw bytes in KiB received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "KB" } },
     "targets": [
      {
       "expr": "sum by(gpu) (nvlink_raw_rx_kib)",
       "legendFormat": "{{ gpu }}"
      }
     ]
    }
   ]
  }
 ]
}